### PR TITLE
Use HTTPS url for meritbadge

### PR DESCRIPTION
**Pull request by dholbert**
Right now this readme file uses an HTTP url to reference a meritbadge image, which ends up producing "broken https" UI on the crates.io page. This patch just upgrades this to an HTTPS url (which still works), to avoid that problem.  (Literally a 1-character change, changing "http" to "https" in "http://meritbadge.herokuapp.com/cargo-update")

### CODE REVIEW

**Comment by dholbert** [comment]
Here's a screenshot of the degraded https UI that this triggers right now on https://crates.io/crates/cargo-update :
screenshot of degraded HTTPS UI

**Comment by nabijaczleweli** [comment]
Thanks for letting me know, I'll look over the rest of my projects and see if I've any HTTP links in them now.

**Comment by nabijaczleweli** [comment]
Looks like I accidentally tagged #7 instead of this in the remaining 22 repositories, damn `vim` copypaste. Oh well.

**Comment by dholbert** [comment]
Thanks!

**Pull request merged**
